on:
  workflow_call:
    secrets:
      SONARCLOUD_SECRET:
        required: true

jobs:
  publish_sonar_cloud:
    name: Publish Sonar Cloud
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Clover Artifact
        id: download_clover
        uses: actions/download-artifact@v3
        with:
          name: clover
          path: coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_SECRET }}
